/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Color: typeof import('./../components/color/index.vue')['default']
    CommonTable: typeof import('./../components/common-table/index.vue')['default']
    LanguageSwitcher: typeof import('./../components/LanguageSwitcher.vue')['default']
    ProductCard: typeof import('./../components/product-card/index.vue')['default']
    Result: typeof import('./../components/result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TColorPickerPanel: typeof import('tdesign-vue-next')['ColorPickerPanel']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    Thumbnail: typeof import('./../components/thumbnail/index.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    Trend: typeof import('./../components/trend/index.vue')['default']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}

// For TSX support
declare global {
  const Color: typeof import('./../components/color/index.vue')['default']
  const CommonTable: typeof import('./../components/common-table/index.vue')['default']
  const LanguageSwitcher: typeof import('./../components/LanguageSwitcher.vue')['default']
  const ProductCard: typeof import('./../components/product-card/index.vue')['default']
  const Result: typeof import('./../components/result/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TBadge: typeof import('tdesign-vue-next')['Badge']
  const TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
  const TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TColorPickerPanel: typeof import('tdesign-vue-next')['ColorPickerPanel']
  const TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDrawer: typeof import('tdesign-vue-next')['Drawer']
  const TDropdown: typeof import('tdesign-vue-next')['Dropdown']
  const TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
  const TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
  const TFooter: typeof import('tdesign-vue-next')['Footer']
  const TForm: typeof import('tdesign-vue-next')['Form']
  const TFormItem: typeof import('tdesign-vue-next')['FormItem']
  const THeader: typeof import('tdesign-vue-next')['Header']
  const THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
  const Thumbnail: typeof import('./../components/thumbnail/index.vue')['default']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TList: typeof import('tdesign-vue-next')['List']
  const TListItem: typeof import('tdesign-vue-next')['ListItem']
  const TLoading: typeof import('tdesign-vue-next')['Loading']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TPopup: typeof import('tdesign-vue-next')['Popup']
  const TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
  const TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
  const Trend: typeof import('./../components/trend/index.vue')['default']
  const TSubmenu: typeof import('tdesign-vue-next')['Submenu']
  const TSwitch: typeof import('tdesign-vue-next')['Switch']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
}